sonar.projectKey=sofiaschanton_PI_M5
sonar.organization=sofiaschanton

# Código fuente
sonar.sources=src

# Tests
sonar.tests=tests

# Excluir cosas que no queremos analizar
sonar.exclusions=artifacts/**,**/__pycache__/**,**/.venv/**,**/venv/**,**/*.ipynb

# Cobertura (la genera pytest-cov)
sonar.python.coverage.reportPaths=coverage.xml
